[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.9.9"
borsh = "0.9"
thiserror = "1.0"

[dev-dependencies]
solana-program-test = "1.9.9"
solana-sdk = "1.9.9"
anyhow = "1.0"
borsh = "0.9"
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]
